{
 "title": "Weaviate stats",
 "time": { "from": "2024-12-23T12:00:00.000Z", "to": "2024-12-23T14:01:42.942Z" },
 "templating": {
  "list": [
   { "name": "Branch", "label": "branch", "query": "main" }
  ]
 },
 "panels": [
  {
   "title": "Recall",
   "type": "timeseries",
   "description": "Recall values with different EF values",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ef, recall AS \"recall_ef16\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 16 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, recall AS \"recall_ef24\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 24 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, recall AS \"recall_ef48\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 48 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, recall AS \"recall_ef128\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 128 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, recall AS \"recall_ef256\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 256 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, recall AS \"recall_ef512\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 512 AND branch = '${Branch}') LIMIT 50 "
    }
   ]
  },
  {
   "title": "Mean latency",
   "type": "timeseries",
   "description": "Latency values with different EF values",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ef, mean_latency AS \"ef16\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 16 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, mean_latency AS \"ef24\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 24 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, mean_latency AS \"ef48\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 48 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, mean_latency AS \"ef128\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 128 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, mean_latency AS \"ef256\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 256 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, mean_latency AS \"ef512\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 512 AND branch = '${Branch}') LIMIT 50 "
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "QPS values with different EF values",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ef, qps AS \"qps_ef16\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 16 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, qps AS \"qps_ef24\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 24 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, qps AS \"qps_ef48\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 48 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, qps AS \"qps_ef128\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 128 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, qps AS \"qps_ef256\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 256 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, qps AS \"qps_ef512\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 512 AND branch = '${Branch}') LIMIT 50 "
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "description": "P99 Latency values with different EF values",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ef, p99_latency AS \"ef16\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 16 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, p99_latency AS \"ef24\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 24 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, p99_latency AS \"ef48\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 48 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, p99_latency AS \"ef128\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 128 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, p99_latency AS \"ef256\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 256 AND branch = '${Branch}') LIMIT 50 "
    },
    {
     "rawSql": "SELECT ef, p99_latency AS \"ef512\", \"timestamp\", branch FROM benchmark_results WHERE (ef = 512 AND branch = '${Branch}') LIMIT 50 "
    }
   ]
  }
 ]
}